### ISSUE TITLE
401 - Unauthorised 

### ISSUE THREAD

**Issue by mrdragalion** [woodendoors7/DiscordFriendInvites#1]
Seems as if there's been some changes to either the way Chrome or Discord is handling this code. We now get the following when trying to generate invites, delete or see invites. So all invites generate with just "0" at the end and no actual link. 

![image](https://github.com/woodendoors7/DiscordFriendInvites/assets/1875745/ccf73740-f63a-4719-8dde-c6013f08cb25)

**Comment by woodendoors7** [comment]
Working on a fix

**Comment by woodendoors7** [comment]
Thank you for bringing this to my attention @mrdragalion, should be fixed in 1.1.0
