### ISSUE TITLE
You don't need this code

### ISSUE THREAD

**Issue by Happypig375** [woodendoors7/DiscordFriendInvites#4]
It's intentional feature, use slash command

![image](https://github.com/user-attachments/assets/01f20b0e-bc7f-4f45-a027-9f12d787bc33)

**Comment by woodendoors7** [comment]
That's a vencord plugin, not a Discord feature - this is for anyone who doesn't use vencord and wants to quickly make an invite.

**Comment by mountaincastle47** [comment]
> It's intentional feature, use slash command
> 
> ![image](https://github.com/user-attachments/assets/01f20b0e-bc7f-4f45-a027-9f12d787bc33)

what plugin?

**Comment by woodendoors7** [comment]
@mountaincastle47 FriendInvites for vencord.

**Comment by mountaincastle47** [comment]
> [@mountaincastle47](https://github.com/mountaincastle47) FriendInvites for vencord.

thanks i'll try it out
